on:
  workflow_run:
    workflows: ["Vercel"]
    types: 
      - completed

jobs:
  capture_vercel_preview_url:
    runs-on: "ubuntu-latest"
    steps:
      - uses: aaimio/vercel-preview-url-action@master
        id: deployments
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.deployments.outputs.vercel_preview_url }}
