on: deployment_status

jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    runs-on: "ubuntu-latest"
    steps:
      - run: echo ${{ github.event.deployment_status.target_url }}
